//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildWatch.DataSource.Common.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDataSourceConfigRequest", Namespace="http://schemas.datacontract.org/2004/07/BuildWatch.ControlServer")]
    [System.SerializableAttribute()]
    public partial class GetDataSourceConfigRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDataSourceConfigResponse", Namespace="http://schemas.datacontract.org/2004/07/BuildWatch.ControlServer")]
    [System.SerializableAttribute()]
    public partial class GetDataSourceConfigResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BuildWatch.DataSource.Common.DataService.ConfigEntry> ConfigEntriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataSourceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BuildWatch.DataSource.Common.DataService.ConfigEntry> ConfigEntries {
            get {
                return this.ConfigEntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigEntriesField, value) != true)) {
                    this.ConfigEntriesField = value;
                    this.RaisePropertyChanged("ConfigEntries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataSourceId {
            get {
                return this.DataSourceIdField;
            }
            set {
                if ((this.DataSourceIdField.Equals(value) != true)) {
                    this.DataSourceIdField = value;
                    this.RaisePropertyChanged("DataSourceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigEntry", Namespace="http://schemas.datacontract.org/2004/07/BuildWatch.ControlServer")]
    [System.SerializableAttribute()]
    public partial class ConfigEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PushFinishedBuildsRequest", Namespace="http://schemas.datacontract.org/2004/07/BuildWatch.ControlServer")]
    [System.SerializableAttribute()]
    public partial class PushFinishedBuildsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BuildWatch.DataSource.Common.DataService.FinishedBuildInfo> BuildInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataSourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BuildWatch.DataSource.Common.DataService.QueuedBuildInfo> QueuedBuildsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BuildWatch.DataSource.Common.DataService.FinishedBuildInfo> BuildInfo {
            get {
                return this.BuildInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildInfoField, value) != true)) {
                    this.BuildInfoField = value;
                    this.RaisePropertyChanged("BuildInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataSourceId {
            get {
                return this.DataSourceIdField;
            }
            set {
                if ((this.DataSourceIdField.Equals(value) != true)) {
                    this.DataSourceIdField = value;
                    this.RaisePropertyChanged("DataSourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BuildWatch.DataSource.Common.DataService.QueuedBuildInfo> QueuedBuilds {
            get {
                return this.QueuedBuildsField;
            }
            set {
                if ((object.ReferenceEquals(this.QueuedBuildsField, value) != true)) {
                    this.QueuedBuildsField = value;
                    this.RaisePropertyChanged("QueuedBuilds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinishedBuildInfo", Namespace="http://schemas.datacontract.org/2004/07/BuildWatch.ControlServer")]
    [System.SerializableAttribute()]
    public partial class FinishedBuildInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildInstanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildInstance {
            get {
                return this.BuildInstanceField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildInstanceField, value) != true)) {
                    this.BuildInstanceField = value;
                    this.RaisePropertyChanged("BuildInstance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildName {
            get {
                return this.BuildNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildNameField, value) != true)) {
                    this.BuildNameField = value;
                    this.RaisePropertyChanged("BuildName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAction {
            get {
                return this.UserActionField;
            }
            set {
                if ((object.ReferenceEquals(this.UserActionField, value) != true)) {
                    this.UserActionField = value;
                    this.RaisePropertyChanged("UserAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueuedBuildInfo", Namespace="http://schemas.datacontract.org/2004/07/BuildWatch.ControlServer")]
    [System.SerializableAttribute()]
    public partial class QueuedBuildInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime QueueTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildName {
            get {
                return this.BuildNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildNameField, value) != true)) {
                    this.BuildNameField = value;
                    this.RaisePropertyChanged("BuildName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime QueueTime {
            get {
                return this.QueueTimeField;
            }
            set {
                if ((this.QueueTimeField.Equals(value) != true)) {
                    this.QueueTimeField = value;
                    this.RaisePropertyChanged("QueueTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PushFinishedBuildsResponse", Namespace="http://schemas.datacontract.org/2004/07/BuildWatch.ControlServer")]
    [System.SerializableAttribute()]
    public partial class PushFinishedBuildsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BuildWatch.DataSource.Common.DataService.QueryInfo> AdditionalQueriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BuildWatch.DataSource.Common.DataService.QueryInfo> AdditionalQueries {
            get {
                return this.AdditionalQueriesField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalQueriesField, value) != true)) {
                    this.AdditionalQueriesField = value;
                    this.RaisePropertyChanged("AdditionalQueries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryInfo", Namespace="http://schemas.datacontract.org/2004/07/BuildWatch.ControlServer")]
    [System.SerializableAttribute()]
    public partial class QueryInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuildWatch.DataSource.Common.DataService.QueryBuildRangeInfo QueryBuildRangeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuildWatch.DataSource.Common.DataService.QueryBuildRangeInfo QueryBuildRange {
            get {
                return this.QueryBuildRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryBuildRangeField, value) != true)) {
                    this.QueryBuildRangeField = value;
                    this.RaisePropertyChanged("QueryBuildRange");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryBuildRangeInfo", Namespace="http://schemas.datacontract.org/2004/07/BuildWatch.ControlServer")]
    [System.SerializableAttribute()]
    public partial class QueryBuildRangeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RangeFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RangeToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildName {
            get {
                return this.BuildNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildNameField, value) != true)) {
                    this.BuildNameField = value;
                    this.RaisePropertyChanged("BuildName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RangeFrom {
            get {
                return this.RangeFromField;
            }
            set {
                if ((this.RangeFromField.Equals(value) != true)) {
                    this.RangeFromField = value;
                    this.RaisePropertyChanged("RangeFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RangeTo {
            get {
                return this.RangeToField;
            }
            set {
                if ((this.RangeToField.Equals(value) != true)) {
                    this.RangeToField = value;
                    this.RaisePropertyChanged("RangeTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetProtocolVersion", ReplyAction="http://tempuri.org/IDataService/GetProtocolVersionResponse")]
        int GetProtocolVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDataSourceConfig", ReplyAction="http://tempuri.org/IDataService/GetDataSourceConfigResponse")]
        BuildWatch.DataSource.Common.DataService.GetDataSourceConfigResponse GetDataSourceConfig(BuildWatch.DataSource.Common.DataService.GetDataSourceConfigRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/PushFinishedBuilds", ReplyAction="http://tempuri.org/IDataService/PushFinishedBuildsResponse")]
        BuildWatch.DataSource.Common.DataService.PushFinishedBuildsResponse PushFinishedBuilds(BuildWatch.DataSource.Common.DataService.PushFinishedBuildsRequest req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : BuildWatch.DataSource.Common.DataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<BuildWatch.DataSource.Common.DataService.IDataService>, BuildWatch.DataSource.Common.DataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetProtocolVersion() {
            return base.Channel.GetProtocolVersion();
        }
        
        public BuildWatch.DataSource.Common.DataService.GetDataSourceConfigResponse GetDataSourceConfig(BuildWatch.DataSource.Common.DataService.GetDataSourceConfigRequest req) {
            return base.Channel.GetDataSourceConfig(req);
        }
        
        public BuildWatch.DataSource.Common.DataService.PushFinishedBuildsResponse PushFinishedBuilds(BuildWatch.DataSource.Common.DataService.PushFinishedBuildsRequest req) {
            return base.Channel.PushFinishedBuilds(req);
        }
    }
}
